---
openapi: "3.0.1"
info:
  title: "DSAO Subscription"
  description: "This API specification describes the data structures used in the requests\
    \ and responses relating to DSAO subscription. It allows the consumer of the API\
    \ to create a subscription in ETMP.\n\nThe consumer sends a request with idType,\
    \ idNumber. The API will then respond with the corresponding details of dsaoIdNumber\
    \ for successful subscription or an appropriate error message.\n\nThe interface\
    \ is implemented as a synchronous REST service.\n\n**EPID references:** \n- EPID1731\
    \ - HIP OAS \n- EPID1730 - MDTP to ETMP DSAO Subscription API\n \n```\nChange\
    \ Log\n  ```\n | Version | Date | Author| Description ||\n|---|----|------|-----|-----|\n\
    \ |0.1.1 | 24-04-2026 | Pradeep Nair| Initial draft (EPID1731 v0.1)||\n
    \ |0.2.1 | 21-05-2026 | Pradeep Nair| Changes for DSAO (Oct 2026)\n
      | | | |1. Removed subscriptionDetails container from request schema|\n
      | | | |2. Updated length of field dsaoIdNumber from 30 to 15 in the response schema|\n
      | | | |3. Added field dsaoIdNumber in 422 error schema|\n
      | | | |4. Updated request and response examples|\n"
  version: "0.2.1"
  termsOfService: "http://INSERT_LINK_TO_SLA_HERE"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0"
  x-integration-catalogue:
    api-type: "SIMPLE"
    backends: "ETMP"
    domain: "8"
    platform: "HIP"
    reviewed-date: "2026-05-01T12:00:00Z"
    short-description: "DSAO Subscription"
    status: "BETA"
    sub-domain: "8.17"
servers:
  - url: "http://etmp-egress-gateway.egress.svc.cluster.local"
    description: "Egress Gateway to ETMP TEST"
tags:
  - name: "dsao"
    description: "Digital Senior Accounting Officer"
paths:
  /RESTAdapter/dsao/subscription:
    post:
      deprecated: false
      summary: "Consumer to ETMP DSAO Subscription"
      description: "This is an operation that will allow synchronous creation of ETMP\
        \ DSAO subscription.\n\nOnce the message is processed in ETMP the API will\
        \ respond with either the corresponding details or an appropriate error message.\n\
        \n**EPID reference:** \n- EPID1731 - HIP OAS\n- EPID1730 - MDTP to ETMP DSAO\
        \ Subscription API\n"
      operationId: "CreateDSAOSubscription"
      tags:
        - "dsao"
      parameters:
        - name: "X-Transmitting-System"
          in: "header"
          description: "Intermediary system that performs the transmission of the message.\
          \ Fixed value of 'HIP' required."
          required: true
          deprecated: false
          allowEmptyValue: false
          style: "simple"
          schema:
            type: "string"
            enum:
              - "HIP"
            example: "HIP"
        - name: "X-Originating-System"
          in: "header"
          description: "Name of the system/service that is the originator of the message and uniquely identifies the consumer of this API. When the consumer is Digital, value 'MDTP' required."
          required: true
          deprecated: false
          allowEmptyValue: false
          style: "simple"
          schema:
            type: "string"
            minLength: 1
            maxLength: 30
            example: "MDTP"
        - name: "correlationid"
          in: "header"
          description: "Unique alphanumeric acknowledgement reference number used for correlation purposes. Must be generated by the originating system. Must conform to 36-character UUID (formatted)."
          required: true
          deprecated: false
          allowEmptyValue: false
          style: "simple"
          schema:
            pattern: "^[0-9a-fA-F]{8}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{12}$"
            type: "string"
          example: "f0bd1f32-de51-45cc-9b18-0520d6e3ab1a"
        - name: "X-Receipt-Date"
          in: "header"
          description: "The time the message was created by the system sending the message.\
          \ The value should follow this date-time pattern, and be represented in\
          \ the UTC time zone: yyyy-MM-ddTHH:mm:ssZ."
          required: true
          deprecated: false
          allowEmptyValue: false
          style: "simple"
          schema:
            type: "string"
            format: "date-time"
            example: "2026-05-05T12:05:45Z"
      requestBody:
        description: "Subscription Request"
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestSchema"
            examples:
              Subscription Request:
                value:
                  idType: "UTR"
                  idNumber: "9876543210"
      responses:
        "201":
          description: "Successful Subscription Response"
          headers:
            correlationid:
              $ref: "#/components/headers/correlationidResponseType"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseSchemaSuccess"
              examples:
                Successful Subscription Response:
                  value:
                    success:
                      processingDate: "2026-01-31T09:26:17Z"
                      dsaoIdNumber: "XB0000493000308"
        "400":
          description: "Bad Request"
          headers:
            correlationid:
              $ref: "#/components/headers/correlationidResponseType"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseSystemErrorType"
              examples:
                Bad Request:
                  value:
                    error:
                      code: "400"
                      message: "string"
                      logID: "F51FC4C29B667B3BC5D2331E231786F7"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        "422":
          description: "Unprocessable  -  ETMP validation errors. Errors of this kind\
            \ indicate that ETMP successfully received the data without any technical\
            \ issues, however it is unable to process the data further for the given\
            \ reason.\n  | Code | Text |\n  |---|----|\n 001|No Master Data Found\n\
            \ 002|Business Partner already subscribed for DSAO\n 003|Request could\
            \ not be processed\n 004|Duplicate Submission\n"
          headers:
            correlationid:
              $ref: "#/components/headers/correlationidResponseType"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseEtmpErrorsType"
              examples:
                Request could not be processed:
                  value:
                    errors:
                      processingDate: "2026-01-31T10:26:17Z"
                      code: "003"
                      text: "Request could not be processed"
        "500":
          description: "Internal Server Error"
          headers:
            correlationid:
              $ref: "#/components/headers/correlationidResponseType"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseSystemErrorType"
              examples:
                Internal Server Error:
                  value:
                    error:
                      code: "500"
                      message: "string"
                      logID: "89505FF7D91484D27D33CC1E5E208807"
components:
  headers:
    correlationidResponseType:
      description: "Unique alphanumeric number used for correlation purposes. Generated by the originating system and included in the response. Conforms to 36-character UUID (formatted)."
      style: "simple"
      required: false
      deprecated: false
      schema:
        type: "string"
        pattern: "^[0-9a-fA-F]{8}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{12}$"
  schemas:
    RequestSchema:
      description: "DSAO Subscription Request JSON"
      type: "object"
      properties:
        idType:
          type: "string"
          description: "Type of ID. Fixed value of Unique Taxpayer Reference (UTR)"
          enum:
            - "UTR"
        idNumber:
          type: "string"
          description: "Unique Taxpayer Reference (UTR) number"
          pattern: "^[0-9]{10}$"
      required:
        - "idType"
        - "idNumber"
      additionalProperties: false
    ResponseEtmpErrorsType:
      type: "object"
      properties:
        errors:
          description: "ETMP Business Validation Error Response"
          type: "object"
          properties:
            processingDate:
              type: "string"
              pattern: "^[0-9]{4}-([0][1-9]|[1][0-2])-([0][1-9]|[1-2][0-9]|[3][0-1])T([0-1][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]Z$"
            code:
              type: "string"
              enum:
                - "001"
                - "002"
                - "003"
                - "004"
            text:
              type: "string"
              minLength: 1
              maxLength: 100
            dsaoIdNumber:
              type: "string"
              description: "The DSAO ID number. This is an alphanumeric field"
              minLength: 1
              maxLength: 15
          required:
            - "processingDate"
            - "code"
            - "text"
          additionalProperties: false
      required:
        - "errors"
      additionalProperties: false
    ResponseSchemaSuccess:
      description: "ETMP Get Reversed Financial Transactions API"
      type: "object"
      required:
        - "success"
      additionalProperties: false
      properties:
        success:
          type: "object"
          required:
            - "processingDate"
            - "dsaoIdNumber"
          additionalProperties: false
          properties:
            processingDate:
              type: "string"
              pattern: "^[0-9]{4}-([0][1-9]|[1][0-2])-([0][1-9]|[1-2][0-9]|[3][0-1])T([0-1][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]Z$"
            dsaoIdNumber:
              type: "string"
              description: "The DSAO ID number. This is an alphanumeric field"
              minLength: 1
              maxLength: 15
    ResponseSystemErrorType:
      type: "object"
      properties:
        error:
          description: "SAP PI System Error Response"
          type: "object"
          properties:
            code:
              type: "string"
              enum:
                - "400"
                - "500"
            message:
              type: "string"
              minLength: 1
              maxLength: 5000
            logID:
              type: "string"
              minLength: 32
              maxLength: 32
              pattern: "^[A-F0-9]{32}$"
          required:
            - "code"
            - "message"
            - "logID"
          additionalProperties: false
      required:
        - "error"
      additionalProperties: false
