---
openapi: 3.0.3
info:
  title: SAO Digital API
  description: |
    APIs supporting the digital management of Senior Accounting Officer (SAO)
    subscriptions, notifications, certificates, and operational contacts.

    Change Log
    ```
    | Version   | Date       | Author     | Description |
    |-----------|------------|------------|---------------|
    |  1.0.2    | 30-06-2026 | Ben Howdle | Initial draft |
    |  1.0.3    | 07-07-2026 | Ben Howdle | Introduce Customer ID + optional submitter |
    |  1.0.4    | 08-07-2026 | Ben Howdle | Max length validation |
    |  1.0.5    | 09-07-2026 | Ben Howdle | Fix OpenAPI formatting |
    |  1.0.6    | 10-07-2026 | Ben Howdle | Remove extra schemas & add validation |
    |  1.0.7    | 14-07-2026 | Ben Howdle | Remove required CRN |
    |  1.0.8    | 21-07-2026 | Ben Howdle | UTR max length |
    |  1.0.9    | 29-07-2026 | Ben Howdle | minLengths, array validation and optional fields |
    ```
  version: 1.0.9
  x-integration-catalogue:
    api-type: SIMPLE
    backends:
    - dsao
    domain: "2"
    platform: HIP
    reviewed-date: 2024-04-25T15:19:20.843477359Z
    short-description: Digitise Senior Accounting Officer API
    status: ALPHA
    sub-domain: "1"
servers:
- url: https://api.ipaas.prod.eis.ns2p.corp.hmrc.gov.uk/dapm
  description: Corporate - Production
- url: https://api.ipaas.preprod.eis.ns2p.corp.hmrc.gov.uk/dapm
  description: Corporate – Pre-Production
- url: https://api.ipaas.test.eis.ns2n.corp.hmrc.gov.uk/dapm
  description: Corporate - Test
- url: https://hip.ws.hmrc.gov.uk/dapm
  description: MDTP - Production
- url: https://hip.ws.ibt.hmrc.gov.uk/dapm
  description: MDTP - QA
paths:
  /subscriptions/{subscriptionId}:
    put:
      tags:
      - Subscription
      summary: Replace an SAO subscription
      description: Fully replaces an existing SAO subscription. This operation is
        idempotent.
      parameters:
      - name: subscriptionId
        in: path
        required: true
        schema:
          maxLength: 15
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionWrite'
            example:
              contacts:
              - email: jane.smith@example.com
                language: en-GB
                name: Jane Smith
                status: valid
              etmpSafeId: XSAFE123456789
              nominatedCompany:
                crn: "09876543"
                name: Example Group Ltd
                utr: "1234567890"
        required: true
      responses:
        "201":
          description: Subscription updated
        "400":
          description: Bad Request
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/HIP-originResponse'
        "500":
          description: Internal Server Error
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/HIP-originResponse'
        "503":
          description: Service Unavailable
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/HIP-originResponse'
      security:
      - oAuth2:
        - write:dsao-submit
  /subscriptions/{subscriptionId}/certificates:
    post:
      tags:
      - Certificate
      summary: Submit an SAO certificate
      description: Submits an SAO certificate as a legal attestation.
      parameters:
      - name: subscriptionId
        in: path
        required: true
        schema:
          maxLength: 15
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CertificateWrite'
            example:
              companies:
              - accPeriodEnd: 2025-03-31
                crn: "11223344"
                isBankLevyQualified: false
                isCorporationTaxQualified: true
                isCustomsDutiesQualified: false
                isExciseDutiesQualified: false
                isInsurancePremiumTaxQualified: false
                isPayeQualified: true
                isPetroleumRevenueTaxQualified: false
                isStampDutyLandTaxQualified: false
                isStampDutyReserveTaxQualified: false
                isVatQualified: true
                name: Example Subsidiary Ltd
                status: active
                type: PLC
                utr: "2233445566"
              saoEmail: jane.smith@example.com
              saoName: Jane Smith
              submitterName: Jane Smith
        required: true
      responses:
        "201":
          description: Certificate submitted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertificateCreated'
        "404":
          description: Subscription not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
        "400":
          description: Bad Request
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/HIP-originResponse'
        "500":
          description: Internal Server Error
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/HIP-originResponse'
        "503":
          description: Service Unavailable
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/HIP-originResponse'
      security:
      - oAuth2:
        - write:dsao-submit
  /subscriptions/{subscriptionId}/notifications:
    post:
      tags:
      - Notification
      summary: Submit an SAO notification
      description: Submits an initial SAO notification for the given subscription.
      parameters:
      - name: subscriptionId
        in: path
        required: true
        schema:
          maxLength: 15
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationWrite'
            example:
              companies:
              - accPeriodEnd: 2025-03-31
                crn: "11223344"
                name: Example Subsidiary Ltd
                status: active
                type: PLC
                utr: "2233445566"
              saos:
              - email: robert.brown@example.com
                fromDate: 2024-04-01
                name: Robert Brown
                toDate: 2025-03-31
        required: true
      responses:
        "201":
          description: Notification submitted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationCreated'
        "404":
          description: Subscription not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
        "400":
          description: Bad Request
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/HIP-originResponse'
        "500":
          description: Internal Server Error
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/HIP-originResponse'
        "503":
          description: Service Unavailable
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/HIP-originResponse'
      security:
      - oAuth2:
        - write:dsao-submit
components:
  schemas:
    CertificateCompany:
      required:
      - utr
      - name
      - accPeriodEnd
      - status
      - type
      - isCorporationTaxQualified
      - isVatQualified
      - isPayeQualified
      - isInsurancePremiumTaxQualified
      - isStampDutyLandTaxQualified
      - isStampDutyReserveTaxQualified
      - isPetroleumRevenueTaxQualified
      - isCustomsDutiesQualified
      - isExciseDutiesQualified
      - isBankLevyQualified
      type: object
      properties:
        accPeriodEnd:
          format: date
          type: string
        crn:
          maxLength: 8
          type: string
        isBankLevyQualified:
          type: boolean
        isCorporationTaxQualified:
          type: boolean
        isCustomsDutiesQualified:
          type: boolean
        isExciseDutiesQualified:
          type: boolean
        isInsurancePremiumTaxQualified:
          type: boolean
        isPayeQualified:
          type: boolean
        isPetroleumRevenueTaxQualified:
          type: boolean
        isStampDutyLandTaxQualified:
          type: boolean
        isStampDutyReserveTaxQualified:
          type: boolean
        isVatQualified:
          type: boolean
        name:
          maxLength: 160
          minLength: 1
          type: string
        qualificationStatement:
          maxLength: 32767
          type: string
        status:
          maxLength: 20
          minLength: 1
          type: string
        type:
          maxLength: 10
          minLength: 1
          type: string
        utr:
          maxLength: 10
          minLength: 1
          type: string
    CertificateCreated:
      required:
      - certificateRef
      type: object
      properties:
        certificateRef:
          maxLength: 16
          type: string
    CertificateWrite:
      required:
      - saoEmail
      - saoName
      - companies
      type: object
      properties:
        companies:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/CertificateCompany'
        customerId:
          maxLength: 10
          type: string
        remarks:
          maxLength: 32767
          type: string
        saoEmail:
          format: email
          maxLength: 254
          minLength: 1
          type: string
        saoName:
          maxLength: 254
          minLength: 1
          type: string
        staffPid:
          maxLength: 30
          type: string
        submitterName:
          maxLength: 254
          type: string
    ContactWrite:
      required:
      - name
      - email
      - status
      - language
      type: object
      properties:
        email:
          format: email
          maxLength: 254
          minLength: 1
          type: string
        language:
          maxLength: 5
          minLength: 1
          type: string
        name:
          maxLength: 254
          minLength: 1
          type: string
        status:
          maxLength: 20
          minLength: 1
          type: string
    ErrorObject:
      required:
      - timestamp
      - errors
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorResponse'
        timestamp:
          maxLength: 20
          type: string
    ErrorResponse:
      type: object
      properties:
        code:
          maxLength: 75
          type: string
        message:
          maxLength: 500
          type: string
    NominatedCompany:
      required:
      - name
      - utr
      type: object
      properties:
        crn:
          maxLength: 8
          type: string
        name:
          maxLength: 160
          minLength: 1
          type: string
        utr:
          maxLength: 10
          minLength: 1
          type: string
    NotificationCompany:
      required:
      - utr
      - name
      - accPeriodEnd
      - status
      - type
      type: object
      properties:
        accPeriodEnd:
          format: date
          type: string
        crn:
          maxLength: 8
          type: string
        name:
          maxLength: 160
          minLength: 1
          type: string
        status:
          maxLength: 20
          minLength: 1
          type: string
        type:
          maxLength: 10
          minLength: 1
          type: string
        utr:
          maxLength: 10
          minLength: 1
          type: string
    NotificationCreated:
      required:
      - notificationRef
      type: object
      properties:
        notificationRef:
          maxLength: 16
          type: string
    NotificationWrite:
      required:
      - companies
      - saos
      type: object
      properties:
        companies:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/NotificationCompany'
        customerId:
          maxLength: 10
          type: string
        remarks:
          maxLength: 32767
          type: string
        saos:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/SAO'
        staffPid:
          maxLength: 30
          type: string
    SAO:
      required:
      - name
      type: object
      properties:
        email:
          format: email
          maxLength: 254
          type: string
        fromDate:
          format: date
          type: string
        name:
          maxLength: 254
          minLength: 1
          type: string
        toDate:
          format: date
          type: string
    SubscriptionWrite:
      required:
      - etmpSafeId
      - nominatedCompany
      - contacts
      type: object
      properties:
        contacts:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/ContactWrite'
        etmpSafeId:
          maxLength: 15
          minLength: 1
          type: string
        nominatedCompany:
          $ref: '#/components/schemas/NominatedCompany'
    HIP-originEnum:
      enum:
      - HIP
      - HoD
      type: string
    HIP-failureResponse:
      required:
      - failures
      type: object
      properties:
        failures:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - type
            - reason
            type: object
            properties:
              type:
                type: string
              reason:
                type: string
            additionalProperties: false
    HIP-originResponse:
      required:
      - origin
      - response
      type: object
      properties:
        origin:
          $ref: '#/components/schemas/HIP-originEnum'
        response:
          $ref: '#/components/schemas/HIP-failureResponse'
      additionalProperties: false
  securitySchemes:
    oAuth2:
      type: oauth2
      description: OAuth2 Client Credentials Flow
      flows:
        clientCredentials:
          tokenUrl: /tokenUrl/not-required
          scopes:
            write:dsao-submit: Scope for DSAO Submit
